name: punctured_text_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.4.2
  - ca-certificates=2024.12.31
  - deprecated=1.2.13
  - filelock=3.13.1
  - fsspec=2024.12.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libprotobuf=4.25.3
  - libstdcxx-ng=11.2.0
  - libtorch=2.5.1
  - libuv=1.48.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.2.1
  - numexpr=2.10.1
  - openssl=3.0.15
  - opentelemetry-api=1.26.0
  - pandas=2.2.3
  - pip=24.2
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytorch=2.5.1
  - pytz=2024.1
  - readline=8.2
  - sleef=3.5.1
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tzdata=2025a
  - xz=5.4.6
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==24.3.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - cachetools==5.5.2
      - cairocffi==1.7.1
      - cairosvg==2.7.1
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - comm==0.2.2
      - contourpy==1.3.0
      - cssselect2==0.7.0
      - cycler==0.12.1
      - datasets==3.6.0
      - debugpy==1.8.12
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - distro==1.9.0
      - drjit==0.4.6
      - editdistpy==0.1.5
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - fqdn==1.5.1
      - frozenlist==1.6.0
      - gast==0.6.0
      - google-auth==2.38.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - ipydatawidgets==4.3.2
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.0.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - jiter==0.8.2
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.5
      - keras==2.15.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mistune==3.1.0
      - mitsuba==3.5.2
      - ml-dtypes==0.3.2
      - multidict==6.4.3
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nltk==3.9.1
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - oauthlib==3.2.2
      - openai==1.60.0
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - packaging==24.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.3.1
      - protobuf==4.25.6
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-json-logger==3.2.1
      - pythreejs==2.4.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.36.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.22.3
      - rsa==4.9
      - safetensors==0.5.2
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - send2trash==1.8.3
      - setuptools==78.1.0
      - sionna==0.19.2
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - symspellpy==6.7.8
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - traittypes==0.2.1
      - transformers==4.48.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.0
      - unidecode==1.4.0
      - uri-template==1.3.0
      - urllib3==2.3.0
      - w3lib==2.3.1
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - wheel==0.45.1
      - widgetsnbextension==4.0.13
      - wrapt==1.14.1
      - xxhash==3.5.0
      - yarl==1.20.0
